# Generated by Django 3.1.2 on 2020-10-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201006_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='title',
            field=models.CharField(default='test', max_length=200, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
