# Generated by Django 3.1.2 on 2020-10-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201010_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='title',
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='company name', max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
